### ISSUE TITLE
OAuth2 client flow for Quickbooks

### ISSUE THREAD

**Issue by karneaud** [M-E-Development-Design/invoiceninja#17]
@turbo124 

Below is an update on the progress so far...

https://github.com/M-E-Development-Design/invoiceninja/commits/addon/intuit-sdk/

I am approaching the development of the Oauth2 process and wanted some feedback, Base on current import implementations users would select which entities to import, upload the files and import would be performed. Thus the current flow would be in summary

- Select Entity->Pre Import->Import

Given that the Quickbooks implementation requires an extra approach and does not involve upload what would be the expected user flow?

- [ ]  Select Entities -> Authorize -> Pre Import -> Import
- [x]  Authorize -> Select Entities -> Pre Import -> Import
- [ ]  Select Entities -> Authorize -> Import

**Comment by turbo124** [comment]
Just to pad this out for you. The vision in the UI is that the user authenticates, and then post authentication they toggle on/off in the UI which entities they wish to "sync"

**Comment by karneaud** [comment]
Discussion moved [here](https://github.com/M-E-Development-Design/invoiceninja/discussions/21)
