### ISSUE TITLE
500 Server Error when add payment via Bank Transfer method

### ISSUE THREAD

**Issue by karneaud** [M-E-Development-Design/invoiceninja#25]
## Setup
- Version: Latest
- Environment: Shared Hosting

## Interface
- Flutter: []
- React: [x]
- Both: []

## Describe the bug
Client get 500 Server Error when trying to add payment method via "Bank Transfer" method

### Steps To Reproduce

Should not have been able to choose Bank Transfer as payment method.

### Expected Behavior

Should have used ACSS Debit 

## Additional context
Bank Transfer method reserved for US Banks

### Screenshots

[Video](https://github.com/user-attachments/assets/465c2ab9-a23d-4132-8151-942e6a7ad94f)

**Comment by turbo124** [comment]
patched
